<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>zlib.net</AssemblyName>
    <RootNamespace>zlib</RootNamespace>
    <Version>1.0.3</Version>
    <Product>ZLIB.NET</Product>
    <Company>ComponentAce</Company>
    <Copyright>ComponentAce</Copyright>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
